<?php include 'header.php' ?>
<section  class="terms-and-condition">
  <div class="auto-container">
    <div class="terms-condition-row">
      <div class="terms-condition-content">
      <div class="terms-content-title">
        <h1>Terms and Conditions</h1>
      </div>
        <p>Participation in the online sports wagering, fantasy sports, casino games, horse and dog racebook, and free entry or pay for play tournament games (collectively the "Gaming System") is open to residents of legal age in a jurisdiction of residence, where the Gaming System is not prohibited. Employees of Jolly Lotto (the "Company"), its licensees, distributors, affiliates, and subsidiaries are not eligible to participate in the Gaming System. A person who participates in the Gaming System is hereafter called "Player" or "Customer".</p>
        <p>By opening an account, use and reuse of such an account, participating in the Gaming System, or acceptance of any prize, the Player represents, warrants, and certifies all of the following:</p>
        <div class="terms-list">
          <ul>
            <li>The player becomes a party to the terms and conditions specified by Jolly Lotto and agrees to abide by these terms and conditions, including any revisions which may periodically take place. At least once a month, the Player agrees to review the terms and conditions on the website.
            </li>
            <li>The Games are subject to the laws and regulations of the nation of Curacao.</li>
            <li>The Player fully understands the standards and laws, as such standards and laws related to the Gaming System, of the community/legal jurisdiction where he/she is resident. The Player has the complete and unrestricted legal right to participate in the Gaming System. The Player's participation in the Gaming System is not prohibited by any government with proper jurisdiction.</li>
            <li>The Player has reached the age of 18 or the legal age of majority in his/her jurisdiction, whichever is greater.</li>
            <li>A player shall not allow any other person or a third party; including, without limitation, any minor, to use or reuse Player's account, accept any prize, or participate in the Gaming System.</li>
            <li>Players are forbidden from creating multiple accounts. Multiple accounts with the same name, address, or IP address shall be considered one and the same. If it is determined that multiple accounts have been created, Jolly Lotto reserves the right to confiscate any winnings incurred throughout the duration of the registered account(s) and all sports wagers will be void.</li>
            <li>Accounts Open in Our Discretion: We reserve the right to suspend, disable, or terminate your Account at any time in our sole discretion. Unless otherwise required or directed by the Gaming Commission in accordance with the relevant provisions of the Regulations, all decisions regarding the opening, maintenance, and closing of Accounts rest with us and any decisions we take regarding any aspect of the Software, your participation in or the playing of the Games or any aspect of an Account is final.</li>
            <li>Personal Information: The Player acknowledges and agrees that the Company may confirm the accuracy of any information that was submitted, with the use of Third-Party Verification services to authenticate the account information and identity of a Player.</li>
            <ul>
              <li>A Player acknowledges that the Company performs random security checks to maintain a high level of security to protect a Player’s funds. The Player hereby accepts that the Company maintains the right to demand additional documentation in order to verify his personal information, as the account holder in the event of a said security check.</li>
              <li>If a Player provides personal information and is unable or unwilling to provide documentation to confirm his personal details, and if the Company is not able to confirm the Player’s identity, the Account may be terminated. Any, and all activity within the time that the Account was open, up to the point when it was deemed invalid/unverifiable, shall be considered null and void. All winnings, pending wagers as well as pending withdrawals will be forfeited.</li>
            </ul>
            <li>By registering an account, you grant the Company the right to disclose your identity and any information that you have provided in connection to your account, to anyone who makes a claim or allegation that:</li>
            <ul>
              <li>You are a minor or under the minimum age required to make use of any part of the Website; or</li>
              <li>Any Posting or other material posted or uploaded by you to the Website which may constitute a violation of any other Player or person’s intellectual property rights, or of their right to privacy or was otherwise posted or uploaded in breach of these Terms and Conditions</li>
              </ul>
            <li>To deposit funds in your Account you must first supply such information as is required, which will depend upon the method of payment that you select for making the deposit. Once you have supplied the required information, you will be able to make a deposit request from the cashier page of your Account.</li>
            <li>If the player chooses to place any wagers or to play any Games or participate in any tournaments for money, your money will be deposited with and held by us or a third-party service provider(s) pending the outcome of the relevant event, Game, or tournament. Each of the above arrangements is in accordance with these Terms of Service, and the gambling and other laws of Curacao</li>
            <li>We reserve the right to place a limit on the number of funds that you will be able to deposit at any time at a level that we may determine at our sole discretion. You may request that this deposit limit be altered by contacting our Customer Service team at 1-XXX-XXXX or EMAIL</li>
            <li>During the Account true process, the Company may offer an application designed for attempting to limit deposits made by a Player within a particular time period, as determined by the Player. As there are multiple options in which a Player may make a deposit(s), no representations whatsoever are made as to the effectiveness of such application. The Player, therefore, accepts sole responsibility for all deposits made with the Company, regardless of any pre-selected deposit limitation.</li>
            <li>Neither the Company, nor any of its service providers, shall be under any obligation to accept a Player’s deposit request, and the Company shall notify the Player if the deposit request is rejected. If a Player’s deposit is accepted, the Company shall ensure that funds equal to those specified in the Player’s deposit request are credited to the Player’s Account within a reasonable period of time.</li>
            <ul>
              <li>Neither the Company, nor any of its service providers, shall be under any obligation to accept a Player’s deposit request, and the Company shall notify the Player if the deposit request is rejected. If a Player’s deposit is accepted, the Company shall ensure that funds are credited to the Player’s Account within a reasonable period of time; however, the amounts may vary from the intended deposit amount depending on the wallet use and conversion rate.</li>
            </ul>
            <li>If a deposit is disputed (or “charged back”) or is otherwise uncollectible for any reason, any and all winnings generated from play or bets conducted in such Account from the time of the applicable deposit until its reversal or failure of collectability shall be invalidated, forfeited and deducted from a Player’s Account balance. In addition, the amount of the initial failed deposit will be invalidated, forfeited, and deducted from the Account balance. In the event that, following such deductions, a Player’s Account balance resulted in a “negative balance”, he expressly acknowledges and agrees that such negative balance shall constitute an incontestable debt payable by the Player to the Company, due and payable immediately.</li>
            <ul>
              <li>If a deposit is disputed or is otherwise uncollectible for any reason, any and all winnings generated from play or bets conducted in such Account from the time of the applicable deposit until its reversal or failure of collectability shall be invalidated, forfeited, and deducted from a Player’s Account balance. In addition, the amount of the initial failed deposit will be invalidated, forfeited, and deducted from the Account balance. In the event that, following such deductions, a Player’s Account balance resulted in a “negative balance”, he expressly acknowledges and agrees that such negative balance shall constitute an incontestable debt payable by the Player to the Company, due and payable immediately.</li>
              <li>Note that following the assignment of such debt to a collections agency, the resolution of such debt and any legal processes associated therewith are not within the Company’s control and must be negotiated or resolved directly with such collections agency. In addition, a Player who defaults on deposits may be put on industry "blacklists" and may be refused entry to other similar websites</li>
              <li>A Player also expressly acknowledges and agree that, in the event of non-payment of such debt, we may assign such debt to one or more collections agencies, who shall have the legal right to pursue such assigned debt using any or all available legal remedies.</li>
              <li>Note that following the assignment of such debt to a collections agency, the resolution of such debt and any legal processes associated therewith are not within the Company’s control and must be negotiated or resolved directly with such collections agency. In addition, a Player who charges back deposits may be put on industry "blacklists" and may be refused entry to other similar websites</li>
            </ul>
            <li>No Liability for Errors/Omissions: Jolly Lotto shall not be responsible or liable for any errors, mistakes, omissions, or inaccuracies of information or content provided on our Site when depositing; you accept and acknowledge that we are not liable or responsible for any errors or omissions that are made in connection with any Virtual Currency Transaction initiated via the Services. We strongly encourage you to review your transaction details carefully before attempting to deposit using your coin wallet.</li>
            <li>Taxes and fees in connection with any awarded prize are the sole responsibility of the Player. Prizes cannot be transferred, substituted, or redeemed for any other prize</li>
            <li>The Player's participation in the Gaming System is personal and not professional. Jolly Lotto reserves the right to limit steam plays, wise guy action, actions considered by site management as bonus abuse, arbitrage, cross-site hedge bets, horse pool manipulation, fraud or security risk, and any other actions deemed by management that purposefully or accidentally circumvent site or bonus rules and regulations.</li>
            <li>Abuse of System Vulnerability - The Company has a zero-tolerance policy towards inappropriate play and fraudulent activity. If, in Jolly Lotto's sole determination, you are found to have cheated, attempted to defraud the Company or any other user of any of the Games in any way including but not limited to game manipulation, Abuse of System Vulnerability, payment fraud or if the Company suspects you of fraudulent payments, including use of stolen credit cards, coin wallets or any other fraudulent activity or prohibited transaction (including money laundering), the Company reserves the right to suspend and/or close your Account and to share this information (together with your identity) to other online gaming sites, banks, and appropriate agencies.</li>
            <li>Malfunction, System, or Human Error - Jolly Lotto reserves the right to void any winnings that were obtained as a result of hardware/software error, malfunction, or human error. In the event of any such malfunction or error, all wagers and winnings are void.</li>
            <li>Use by players of external player assistance programs ("EPA Programs") which are designed to provide players with an unfair advantage over their opponents are expressly prohibited. We define EPA Programs as including computer software and non-software-based databases or profiles (e.g., web sites and subscription services) and we consider access to or the ability to gather data or information on other players by any means that would not be accessible via their own first-hand experience (i.e. observation of gameplay) to be "unfair". We reserve the right to close Accounts and void any and all winnings in such Accounts if we establish, in our reasonable discretion, the use of an EPA Program.</li>
            <li>The Player acknowledges that full freedom from errors or incompleteness is impossible to achieve with respect to computer software. Should a Player become aware that the software contains an obvious error or incompleteness, he undertakes to refrain from taking any advantage whatsoever thereof. Moreover, promptly upon becoming aware of such error or incompleteness, the Player shall notify the Company in writing or by calling the Jolly Lotto Customer Service team at EMAIL</li>
            <ul>
              <li>Regardless of whether a Player becomes aware of any such errors, the Company shall not be held liable for payment of any sort which may become due as a result of software, administrative, hardware failure, faults, or technical difficulties.</li>
              <li>Should a Player fail to fulfill his undertakings under this clause, the Company, or anyone appointed by the Company, shall be entitled to full compensation for all costs, including costs for rectifying the software, that may be referred to the error or incompleteness in question and Player’s commission to notify the Company.</li>
            </ul>
            <li>A "Dormant Account" is defined as an Account that has not made a deposit, withdrawal, or placed a bet/wager for a period of eighteen (18) months.</li>
            <ul>
              <li>At eighteen months (or 540 days) of inactivity, the Company will send an email notification to the email address registered to the dormant account, advising that the Account balance will be forfeited, thirty (30) days from the notice.</li>
              <li>If the Account remains dormant following this notice, a second "FINAL" email notice will be forwarded at 567 days, again advising of the pending forfeiture of Account balance within 3 days.</li>
              <li>If the Account remains dormant, at 571 days of inactivity, the Account balances are zeroed out.</li>
            </ul>
            <li>Any dispute arising out of or relating to the Gaming, prizes, web site, client application, Jolly Lotto; and/or any e-commerce provider utilized shall be governed by the laws of Curacao, excluding choice of law principles.</li>
            <li>Players of Jolly Lotto are eligible to receive free money bonuses from time to time, including a free money bonus when signing up and for referrals. Said free money bonuses, as to its amount and issuance, shall be subject to the discretion of Jolly Lotto and shall be non-transferable and non-refundable. Free Money can only be spent along with real money at a pre-determined ratio set by the casino and sportsbook manager, and these ratios are available to view in the Help Section of the Jolly Lotto website. Contact our Customer Service team for specific bonus rules if you have further questions about bonuses.</li>
            <li>In regards to BTC or crypto payouts, we will payout to the address sent by the player, and the company is in no way responsible for any mistakes made by the player when sending the wallet address, nor any Bitcoin/crypto-related software or service, e.g., forgotten passwords, accidental deletion of wallets unauthorized access to users' wallets and/or accounts, etc. If you have any questions regarding this process please contact the customer support team</li>
            <li>Any amount withdrawn by the Player shall be forwarded to the Player pending the results of satisfactory anti-fraud and anti-money laundering screening processes. We reserve the right to request additional forms of identification before sending a withdrawal. If a withdrawal is made before the Terms Conditions are met, all withdrawals will be canceled.</li>
            <li>Jolly Lotto shall reserve the right to suspend or withdraw any game at its' absolute discretion.</li>
            <li>All personal details of all users will be held in confidence unless users agree to their identities and details being used for future publicity purposes.</li>
            <li>In the event of the cancellation of any game, sports event or horse or dog race event, for any reason, Jolly Lotto will not be liable.</li>
            <li>Jolly Lotto will not be liable in the following scenarios:</li>
            <ul>
              <li>in the event of force majeuree</li>
              <li>the failure of Jolly Lotto's central computer system or any part thereof</li>
              <li>for delays, losses, errors, or omissions resulting from the failure of any telecommunications or any other data transmission system</li>
              <li>for any loss as a result of any act of God</li>
              <li>for an outbreak of hostilities, riot, civil disturbance, acts of terrorism</li>
              <li>for the acts of Government or authority (including refusal or revocation of any license or consent)</li>
              <li>for fire, explosion, flood, theft, malicious damage, strike, lockout, or industrial action of any kind</li>
              <li>for any disturbance, disruption, or loss caused by pandemic or illness or regulations related to such pandemic or illness.</li>
            </ul>
            <li>Jolly Lotto accepts no liability for any damages, which may be caused to the Player by the interception or misuse of any information transmitted over the Internet.</li>
            <li>These Terms and Conditions constitute the entire Agreement and understanding between Jolly Lotto and the Player. In the event of there being a discrepancy between the English language version of these Terms and Conditions and any other language version, the English language version will be deemed to be correct.</li>
            <li>Players may only win a maximum dollar amount of $25,000.00 per week, this includes individual bets and cumulative totals. Jolly Lotto reserves the right to refuse or limit any wager. However, winnings resulting from the Parlay Challenge and Progressive Jackpots are exceptions to the weekly win maximum limits.</li>
            <ul>
              <li>Based on the player history and account status, Jolly Lotto has payout limits stating how much can be paid out with each Payout request. If the winning balance is more than the said payout limit, the players will have to request consecutive payouts</li>
              <li>Jolly Lotto will provide a 1-time free payout for each player. For further details on the free payout or payout fees, please contact our Customer Service.</li>
            </ul>
            <li>By registering for an account and/or participating in any tournament offered on the Site, you acknowledge that all information contained on the Site may be protected, in all forms and media, by one or more valid copyrights, patents, trademarks, trade secrets, or other proprietary rights, and that all such rights are owned by the Site. You may not modify, publish, participate in the transfer or sale of, create derivative works from, or in any way exploit this information, except that you may download one copy for your personal, noncommercial home use only, provided you keep intact all copyright and other proprietary notices.</li>
            <li>By registering for an account, you agree that the Site may display your user name and tournament records. By accepting any prize from the Site, you agree to allow the Site to print, publish, broadcast, and use, worldwide, in any media and at any time, your name, picture, voice, likeness, and/or biographical information for promotional purposes without additional compensation.</li>
            <li>If you send comments or suggestions, including, but not limited to, notes, text, drawings, or computer programs, to the Site, such submissions shall become, and shall remain, the sole property of the Site. No submission shall be subject to any obligation of confidence on the part of the Site. The Site shall exclusively own all rights to and shall be entitled to unrestricted use of, all such submissions without compensation to you.</li>
            <li>The Website and the Services are intended solely for recreational, entertainment purposes. We are committed to ensuring that players have the ability to manage or limit their play on the Website. If gambling is negatively affecting your personal or professional life, please refer to the resources available here to seek counsel or assistance. The site footer has a link or links to responsible gaming resources.</li>
            <li>Within the account registration process, Company may offer an application designed for attempting to limit deposits made by Player within a particular time period, as determined by Player. As there are multiple options in which Player may make a deposit(s), no representations whatsoever are made as to the effectiveness of such application. Player, therefore, accepts sole responsibility for all deposits made with Company regardless of any pre-selected deposit limitation.</li>
            <li>You have the option of setting your play limits to zero or completely closing the Account if you believe you have a gambling problem. We honor all such directions immediately. Please contact Customer service immediately if you feel that you have a gambling problem. Our team will verify your identity and then close your account. Please note that if you close your account due to a gambling problem we will not re-open it under any circumstance.</li>
            <li>Jolly Lotto reserves the right to modify its services offered and the company’s terms and conditions at any time without prior notice. The modification includes but not limited to marketing promotions, bonus policy, game events, site content, deposit and withdrawal policy, requirements and terms, etc. Any changes will be effective immediately upon posting of the revisions on the website. The Player’s continued use of the site following the posting of changes or modifications confirms the player’s full understanding and acceptance.</li>
          </ul>
          <h2>Games of Skill Specific Terms and Conditions</h2>
          <ul>
            <li>The results of all tournaments offered within the Gaming System depend on the number and skill level of the players participating in such tournaments; precise odds of winning are therefore unavailable.</li>
            <li>Prizes are generally cash amounts that are deposited directly into winners' accounts. The cash value of prizes offered in Limited Entry Tournaments will be disclosed at the beginning of such tournaments. If a Limited Entry tournament has to close prematurely, such as for maintenance or technical problems, the prize for the tournament will be proportional to how full the tournament was at the time of closing. The cash value of prizes offered in Unlimited Jackpot Tournaments will depend on the number of participants participating in such tournaments, and will not be available until such tournaments have ended.</li>
            <li>The results and winners of each tournament offered within the Gaming System will be determined by Jolly Lotto. By registering and/or participating in any tournament, you agree to be bound by these determinations.</li>
            <li>In case of a malfunction or disruption of service for which the Gaming System is responsible that prevents you from completing a tournament in which you have begun to participate, the Company will, upon receipt of a refund request, refund the entry fee charged for that unfinished tournament only. The Company reserves the right to determine, in its sole discretion, whether it is responsible for any such malfunction or disruption. The Company reserves the right to limit your tournament play or terminate your account should The Company determine, in its sole discretion, that you have intentionally caused such a malfunction or disruption. The Company is not liable for any potential winnings from any unfinished tournament.</li>
            <li>Jolly Lotto games are played over the Internet which reaches virtually every country in the world. Some of these jurisdictions have not addressed the legality of Internet gaming, while some have specifically made Internet gaming illegal. In practical terms, it is impossible for Jolly Lotto to determine the state of the law in every country, state, and province around the world on an ongoing basis. Therefore, by clicking the "I agree" button, you are taking sole responsibility for your internet activity. Should there be any discrepancy in the legality of any transactions between yourself and Jolly Lotto, or any of its affiliates, the matter shall be determined by a court of competent jurisdiction in the country of Curacao, which is where Jolly Lotto is incorporated and where it conducts business. Any matter to be adjudicated shall be determined utilizing the laws of Curacao.</li>
            <li>All bets with Jolly Lotto are considered to be placed and received in Curacao.</li>
            <li>All contractual issues between yourself and Jolly Lotto, or any of its affiliates, that are disputed, shall be resolved by a court of competent jurisdiction in the country of Curacao.</li>
            <li>All contracts shall be interpreted in accordance with the laws of Curacao.</li>
          </ul>
          <h2>Deposit Bonuses and Free Money</h2>
          <ul>
            <li>When you deposit at Jolly Lotto, your account is awarded a Free Money bonus. First-time depositors will get a generous 150% Free Money Bonus and a 20% Free Money Bonus for subsequent “reload” deposits.</li>
            <li>Your real money and Free Money balances are displayed separately on the website. Real money balances are available to withdraw from the system, while Free Money balances are not. You must meet all eligibility requirements and identification requirements to perform a withdrawal of your real money balance.</li>
          </ul>
          <h2>How Free Money becomes a real money</h2>
          <ul>
            <li>When you play a Casino game or wager on a sports event, a portion of your wager will be comprised of real money and a portion will be comprised of Free Money. All game payouts or sports bet payouts will be to your real money balance. In this fashion, as you wager on the site, your Free Money balance will reduce, and wins will payout into your real money balance.</li>
            <li>Free money cannot be wagered on its own, it must be combined with real money to make your wager. Therefore, you cannot make a wager solely with Free Money, you will need real money in your account to utilize the free money.</li>
            <li>Horse / Harness / Dog wagers made in the racebook do not utilize Free Money, and such wagers must be made with real money balance only.</li>
          </ul>
          <h2>What amounts of Free Money are used in my wagers?</h2>
          <ul>
            <li>The amount of Free Money used in the wager is determined by which game you are playing. For example, you can see in the list below that sports wagers use Free Money at a “39:1” rate. So, if you placed a $40 sports wager, $39 would come from your real money balance while the remaining $1 would come from your free money balance. Likewise, an $80 sports wager would use $2 from Free Money, and a $16.00 sports wager would use $0.40 of Free Money.</li>
            <li>FREE MONEY USAGE RATES</li>
          </ul>
          <div class="money-rates padding-left-30">
            <p>The list below shows the Free Money usage rates as of October 07, 2020. These rates are subject to change and management decision is final.</p>
            <p>19:1 ($19 real money to $1 Free Money) <br>Keno games <br>Sic Bo games</p>
            <p>29:1 ($29 real money to $1 Free Money) <br>Slot games <br>Caribbean Poker <br>American Roulette</p>
            <p>39:1 ($39 real money to $1 Free Money) <br>Sports wagers <br>Live In-game sports wagers</p>
            <p>69:1 ($69 real money to $1 Free Money) <br>Video Poker games <br>European Roulette <br>Pai Gow games</p>
            <p>159:1 ($159 real money to $1 Free Money) <br>Blackjack games <br>Pick-a-number 1-100 games <br>Baccarat games <br>Tri-Card poker games</p>
          </div>
          <h2>INSTANT CASH CREDIT, FREE BET, MANUAL CASH CREDIT, AND NON-DEPOSIT BASED PROMOTION TERMS AND CONDITIONS</h2>
          <div class="money-rates">
            <p>The following terms and conditions are applicable to all promotions where there is NO CUSTOMER DEPOSIT, for example, any INSTANT CASH CREDIT, FREE BETS, MANUAL CASH CREDITS, AND NON-DEPOSIT BASED PROMOTIONS.</p>
            <p>Customers are only entitled to the amount specified by the INSTANT CASH CREDIT or bonus code provided by the company. For example-$350 or $200 Real Money INSTANT CASH CREDIT.</p>
            <p>Any "NON-DEPOSIT BONUSES" can only be used by the customer or prospective client that the bonus code was sent to, or the specific account it was applied to by the company-any sharing of codes or using of other client’s codes will invalidate the bonus and any winnings may be seized by the company.</p>
            <p>Instant cash credits -special bonusing programs for transitioning players from other operators. As a general rule, the previous balance will be added to your free money account, while instant cash credits will be added to the real money balance. However, Instant cash credits are designed to allow you to start playing and unlocking your free money balances, and as such a rollover applies.</p>
            <p>For all NON-DEPOSIT BONUSES, all rollover play-through and payout terms must be completed before the NON-DEPOSIT BONUSES, or any winnings derived from the use of the NON-DEPOSIT BONUSES may be withdrawn or cashed out</p>
            <p>Wagering contributions to meet Rollover requirements on our bonuses are as follows:</p>
            <p>25x play-through rollover: All games and sports wagers except those listed below.</p>
            <p>Exceptions: <br>Wagers on the following games are worth 25% towards your play-through/rollover value: <br><br>Pick-a-number 1-100 games <br>Baccarat games <br>Blackjack games <br>Video Poker games <br>Table games
            </p>
            <p>Some NON-DEPOSIT BONUSES may have different play-through rollover requirements. Any and all decisions made by the company regarding promotional bonus codes, NON-DEPOSIT BONUSES, rollover amounts, and types, and the usage of any promotional code is indisputable and final so it is the customer's responsibility to ensure that they are aware of the requirements associated with the promotion/s that they would like to redeem before placing any/all wager that or use said promotions.</p>
            <p>As well as completing the rollover, in order to get a payout, Customers will need to deposit at least a matching amount of the non-deposit bonus received. For example, if a $350 INSTANT CASH CREDIT/NON-DEPOSIT BONUS was given, the customer would have to deposit a minimum of $350 deposit otherwise the withdrawal request will not be processed.</p>
            <p>All wins from any Instant Cash Credits and None Deposit Bonuses which come eligible for withdrawal after their play-through requirement are limited to a maximum payout of double the Instant Cash Credit/None Deposit Bonuses up to $250.</p>
            <p>For all NON-DEPOSIT BONUSES except free bets, the customer must make at least 10 individual, unrelated wagers in order to complete the rollover requirements of any NON-DEPOSIT BONUSES.</p>
            <p>Examples of invalid, related wagers include (but are not limited to):</p>
          </div>
          <ul class="unorder-list">
            <li>2 or more wagers where the outcome of each wager is directly related to each other such as wagering on red and black in roulette, or Player and Banker in Baccarat on the same spin or hand.</li>
            <li>2 or more wagers on the same sports event.</li>
            <li>2 or more wagers on the same sport's future, such as NBA championship futures or team to win NFL championship futures.</li>
            <li>Any other pair or multiple of wagers that site management deems have related outcomes.</li>
          </ul>
          <div class="money-rates">
            <p>Making a deposit subsequent to completing the rollover and wagering requirements on the first-time deposit bonus does not remove or alter the restriction.</p>
            <p>Customers are subject to other standard withdrawal rules and conditions.</p>
            <p>Forfeiting bonuses will result in bonuses and any subsequent winnings associated with the bonus to be removed.</p>
          </div>
          <h2>Privacy Policy</h2>
          <h2>Please refer to our Privacy Policy page to review Jolly Lotto Privacy Policy Fraud, Money dumping, and Collusion</h2>
          <p>Jolly Lotto also has the right to hold any and all of a player's funds indefinitely if it is found that the player has been involved in fraudulent activity on Jolly Lotto. Fraudulent activity may include but is not limited to, transfer of funds to other player accounts (chip dumping), forgery, and collusion.</p>
          <p>Jolly Lotto also has the right to hold any and all of a player's funds indefinitely if it is found that the player has been involved in fraudulent activity on Jolly Lotto. Fraudulent activity may include, but is not limited to, False claims of lost Bitcoins/wallets, transfer of funds to other player accounts (chip dumping), forgery, and collusion.</p>
          <p>You may only use the Software in accordance with the rules posted on the Jolly Lotto site, as may be modified from time to time. In cases where disputes arise between players, you agree that judgments of Jolly Lotto are final, binding, and conclusive in all matters.</p>
          <p>All taxes, duties, and fees applicable in connection with any money or prizes awarded to a Player are the Player's sole responsibility. Violation of any Jolly Lotto policy or rule may result in suspension or termination of the player's Jolly Lotto account.</p>
          <h2>True Identity and One Account</h2>
          <p>The name on your Account must match your true and legal name and identity and the name on your Jolly Lotto Account registration must match the name on, <b>government-issued identification card</b> or other payment accounts used to deposit or receive monies in your Account. You are prohibited from holding more than one Account at Jolly Lotto. If you have more than one (1) Account or Accounts in different names, then you must contact us immediately to have your Accounts managed so that you only have one (1). If you have lost your Account name or password, please contact us for a replacement.</p>
          <p>All information provided by a player must be accurate and verifiable. If you have provided false information or are unable or unwilling to provide documentation to confirm your information, your account may be terminated and all activity within the account considered invalid.</p>
          <h2>Abusive or Offensive Language</h2>
          <p>Abusive or offensive language will not be tolerated on the chat boards, Games, or otherwise by a Player on Jolly Lotto or with Jolly Lotto staff.</p> 
          <P>Violation of this policy will result in the suspension of playing privileges, or such other action as may be reasonably required by the Company to ensure compliance. In addition, Players are not entitled to make untrue and/or malicious and/or damaging comments with regard to the Company’s operation in any media or forum.</p>
            <h2>Fraudulent Activities and Prohibited Transactions</h2>
            <p>The Company has a zero-tolerance policy towards inappropriate play and fraudulent activity. If, in Jolly Lotto's sole determination, you are found to have cheated or attempted to defraud the Company or any other user of any of the Games in any way including but not limited to game manipulation or payment fraud, or if the Company suspects you of fraudulent payment, including use of stolen credit cards, coin wallets or any other fraudulent activity or prohibited transaction (including money laundering), the Company reserves the right to suspend and/or close your Account and to share this information (together with your identity) to other online gaming sites, banks, and appropriate agencies.</p>
            <h2>Indemnity</h2>
            <p>You agree to hold Jolly Lotto, its employees, officers, directors, licensees, licensors, affiliates, and subsidiaries harmless and further agree to fully indemnify them from any and all costs, expenses, liabilities, and damages whatsoever that may arise as a result of your breach of this Agreement. Moreover, you understand and agree that (without prejudice to your other rights and remedies) Jolly Lotto records shall be the final authority in determining the terms of your participation in the Games, the activity resulting therefrom, and the circumstances in which they occurred.</p>
            <h2>Bonus Abuse</h2>
            <p>At Jolly Lotto's option, a win may be subject to verification by an independent judging organization before any payment is made. Decisions of the judging organization are final, binding, and conclusive in all matters. A player's sole remedy for any error or mistake by Jolly Lotto in connection with a wager placed on Jolly Lotto's system shall be a replacement wager.</p>
            <ul>
              <li>A Player or group of players working together in any fashion, also known as a syndicate, (to receive either eCash winnings or Activity bonuses) may only have one Jolly Lotto account in total, and any redundant Accounts will be consolidated into one account. An administration fee may be charged and payouts refused for each redundant account, at the discretion of the Company.</li>
              <ul>
                <li>All wagering transactions in redundant Accounts are subject to reversal at the sole discretion of the Company. The Company also reserves the right to keep the principle of any wager placed in an attempt to defraud the house of any bonus monies, whether a party does this on their own or in collusion with other players or other sportsbooks. There is no obligation on behalf of the Company to warn players or syndicates of this other than as explained here in the Player Agreement.</li>
              </ul>
              <li>If you lose your account privileges with Jolly Lotto due to misrepresentation, fraud or purchase disputes, the Company reserves the right to terminate a Player’s Account and all transactions from the account in question may be immediately reversed at the sole discretion of the Company.</li>
              <li>From time to time, the Company may run special promotions, contests, tournaments, and may establish rules and regulations governing the conduct of those promotions, contests, and tournaments. The Company or a third party shall post these rules on the Internet, and the Player Service Representatives of Jolly Lotto shall enforce the rules.</li>
              <ul>
                <li>Said promotions, contests, and tournaments may be canceled or suspended at any time without notice by the Company. In the event of an error or omission in the printed rules of a particular promotion, contest, or tournament, the decision of the Company’s Management will be considered final and binding.</li>
              </ul>
              <li>Bonus programs are intended for recreational bettors only. Professional bettors or bettors considered to be abusing the bonus system by any means may have bonuses revoked and be subject to further sanctions, at the discretion of the Company’s management.</li>
              <ul>
                <li>Bonus abuse may be defined as (but not restricted to) clients cashing out for the purpose of redepositing, or referring new Accounts that they are using themselves. Sanctions may be in the form of increased rollover requirements or loss of bonus privileges altogether for the offending account as well as any linked Accounts.</li>
              </ul>
              <li>The Company takes no responsibility for notifying winners other than to update the information available in the wager account summary statement.</li>
              <li>The Company reserves the right to refuse payment to anyone that is found to be party to any organized wagering syndicates dedicated to changing and manipulating the odds available on the Jolly Lotto website.</li>
              <li>At the Company’s discretion, a win may be subject to verification by an independent judging organization before any payment is made. Decisions of the judging organization are final, binding and conclusive in all matters. A player's sole remedy for any error or mistake by the Company in connection with a wager placed on the Jolly Lotto website shall be a replacement wager.</li>
            </ul>
            <h2>Responsible Gaming</h2>
            <p>The Company is committed to ensuring that Players have the ability to manage or limit their play on the Website.</p>
            <p>A Player has the option of setting his play limits to zero or completely closing the Account if he believes that he has a gambling problem. We honor all such directions immediately.</p>
            <p>The Company urges a Player to contact Player Service immediately if he feels that he has a gambling problem. The Customer Service team will verify the Player’s identity and then close the account.</p>
            <p>Please note that if a Player chooses to close the Account due to a gambling problem, the Company will not re-open it under any circumstance.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<?php include 'footer.php' ?>